typo in requirements
requires a '==' instead of a single '=' otherwise you get a pip error
along the lines of:
ValueError: ('Expected version spec in', 'lxml=3.3.3', 'at', '=3.3.3')